//
// Created by maverick on 9/8/23.
//

#ifndef ANALISISNUMERICO_ECUACIONESLINEALES_H
#define ANALISISNUMERICO_ECUACIONESLINEALES_H


class ecuacionesLineales {

};


#endif //ANALISISNUMERICO_ECUACIONESLINEALES_H
